# Use the official Python image from the Docker library
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Command to run the Python script
CMD ["python", "load_bookmarks.py"]
