FROM openjdk:11-jre-slim

# Set environment variables
ENV NUTCH_VERSION 1.18
ENV NUTCH_HOME /opt/nutch
ENV NUTCH_ARCHIVE apache-nutch-$NUTCH_VERSION-bin.tar.gz
ENV NUTCH_URL https://downloads.apache.org/nutch/$NUTCH_VERSION/$NUTCH_ARCHIVE

# Install required packages and keys
RUN apt-get update && \
    apt-get install -y --no-install-recommends gnupg2 dirmngr && \
    rm -rf /var/lib/apt/lists/* && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 648ACFD622F3D138 04EE7237B7D453EC && \
    echo "deb http://deb.debian.org/debian bullseye main" > /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian-security bullseye-security main" >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian bullseye-updates main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and install Nutch
RUN wget $NUTCH_URL && \
    tar -xzf $NUTCH_ARCHIVE -C /opt && \
    mv /opt/apache-nutch-$NUTCH_VERSION $NUTCH_HOME && \
    rm $NUTCH_ARCHIVE

# Set working directory
WORKDIR $NUTCH_HOME

# Expose Nutch ports
EXPOSE 8081 8080
