FROM arm64v8/ubuntu:20.04

# Set environment variables
ENV NUTCH_VERSION 1.18
ENV NUTCH_HOME /opt/nutch
ENV NUTCH_ARCHIVE apache-nutch-$NUTCH_VERSION-bin.tar.gz
ENV NUTCH_URL https://downloads.apache.org/nutch/$NUTCH_VERSION/$NUTCH_ARCHIVE

# Install required packages and keys
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget gnupg && \
    wget -qO - https://www.apache.org/dist/nutch/KEYS | apt-key add - && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and install Nutch
RUN wget $NUTCH_URL && \
    tar -xzf $NUTCH_ARCHIVE -C /opt && \
    mv /opt/apache-nutch-$NUTCH_VERSION $NUTCH_HOME && \
    rm $NUTCH_ARCHIVE

# Set working directory
WORKDIR $NUTCH_HOME

# Expose Nutch ports
EXPOSE 8081 8080
